apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: textrepo-app
  name: textrepo-app
  namespace: textrepo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: textrepo-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: textrepo-app
    spec:
      containers:
      - args:
        - /data/wait-for-it.sh
        - autocomplete-indexer:8080
        - --timeout=0
        - --
        - /data/wait-for-it.sh
        - full-text-indexer:8080
        - --timeout=0
        - --
        - /textrepo-app/start.sh
        env:
        - name: TR_CONTENT_DECOMPRESSION_LIMIT
          value: "1024"
        - name: TR_DATABASE_CHECK_CONNECTION_WHILE_IDLE
          value: "false"
        - name: TR_DATABASE_DRIVER_CLASS
          value: org.postgresql.Driver
        - name: TR_DATABASE_EVICTION_INTERVAL
          value: 10s
        - name: TR_DATABASE_MAX_SIZE
          value: "32"
        - name: TR_DATABASE_MAX_WAIT_FOR_CONNECTION
          value: 1s
        - name: TR_DATABASE_MIN_SIZE
          value: "8"
        - name: TR_DATABASE_PASSWORD
          value: textrepo
        - name: TR_DATABASE_PROPERTIES_CHAR_SET
          value: UTF-8
        - name: TR_DATABASE_URL
          value: jdbc:postgresql://postgres:5432/textrepo
        - name: TR_DATABASE_USER
          value: textrepo
        - name: TR_DATABASE_VALIDATION_QUERY_TIMEOUT
          value: 3s
        - name: TR_DATE_FORMAT
          value: yyyy-MM-dd'T'HH:mm:ss
        - name: TR_FLYWAY_CLEAN_DISABLED
          value: "true"
        - name: TR_FLYWAY_LOCATIONS
          value: '[filesystem:/textrepo-app/db]'
        - name: TR_INDEXERS
          value: |2-

            - name: autocomplete
              mapping: http://autocomplete-indexer:8080/autocomplete/mapping
              types: http://autocomplete-indexer:8080/autocomplete/types
              fields:
                url: http://autocomplete-indexer:8080/autocomplete/fields
                type: multipart
              elasticsearch:
                index: autocomplete
                hosts:
                  - elasticsearch:9200
            - name: full-text
              mapping: http://full-text-indexer:8080/full-text/mapping
              types: http://full-text-indexer:8080/full-text/types
              fields:
                url: http://full-text-indexer:8080/full-text/fields
                type: multipart
              elasticsearch:
                index: full-text
                hosts:
                  - elasticsearch:9200
            - name: file
              mapping: http://file-indexer:8080/file/mapping
              types: http://file-indexer:8080/file/types
              fields:
                url: http://file-indexer:8080/file/fields
                type: multipart
              elasticsearch:
                index: file
                hosts:
                  - elasticsearch:9200
        - name: TR_LOGGING_APPENDERS
          value: |2-

              - type: console
                # Log only first 8 chars of request uuid:
                logFormat: "[%-5p] [%d{ISO8601,UTC}] [%.8X{request}] %logger{32}: %m%n%rEx"
        - name: TR_LOGGING_LEVEL
          value: INFO
        - name: TR_LOGGING_LOGGERS
          value: |2-

                nl.knaw.huc: DEBUG
                # Hide warnings of Swagger trying to load classes through reflection:
                org.reflections.Reflections: ERROR
        - name: TR_PAGINATION_DEFAULT_LIMIT
          value: "10"
        - name: TR_PAGINATION_DEFAULT_OFFSET
          value: "0"
        - name: TR_SWAGGER_CONTEXT_ROOT
          value: /textrepo
        - name: TR_SWAGGER_RESOURCE_PACKAGE
          value: nl.knaw.huc.resources
        - name: TR_SWAGGER_SCHEMES
          value: '[https]'
        image: knawhuc/textrepo-app:1.19.0
        name: gltr-textrepo
        ports:
        - containerPort: 8080
        - containerPort: 8081
        volumeMounts:
          - mountPath: /data
            name: wait-for-it
      restartPolicy: Always
      volumes:
        - name: wait-for-it
          configMap:
            name: wait-for-it
            defaultMode: 0755
