version: '3'

services:
  postgres:
    container_name: tr_postgres
    image: knawhuc/textrepo-postgres:latest
    build: ./postgres
    networks:
    - textrepo_network
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: postgres.textrepo
      POSTGRES_PORT: ${POSTGRES_PORT}

  elasticsearch:
    container_name: tr_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    environment:
    - node.name=es01
    - cluster.initial_master_nodes=es01
    - cluster.name=textrepo-cluster
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
    - esdata:/usr/share/elasticsearch/data
    ports:
    - 9200
    networks:
    - textrepo_network

  nginx:
    container_name: tr_nginx
    image: knawhuc/textrepo-nginx:latest
    build: ./nginx
    networks:
    - textrepo_network
    depends_on:
    - textrepo-app
    volumes:
    - concordiondata:/concordion:ro
    ports:
    - 8080:8080

  autocomplete-indexer:
    container_name: tr_autocomplete
    image: knawhuc/textrepo-autocomplete-indexer:latest
    build: ./elasticsearch/autocomplete
    ports:
      - 8080
    networks:
      - textrepo_network
    command: ["/utils/wait-for-it.sh", "elasticsearch:9200",
              "--timeout=0",
              "--",
              "java", "-jar", "/indexer/autocomplete.jar", "server", "config.yml"]

  full-text-indexer:
    container_name: tr_full-text
    image: knawhuc/textrepo-full-text-indexer:latest
    build: ./elasticsearch/full-text
    ports:
      - 8080
    networks:
      - textrepo_network
    command: ["/utils/wait-for-it.sh", "elasticsearch:9200",
              "--timeout=0",
              "--",
              "java", "-jar", "/indexer/full-text.jar", "server", "config.yml"]

  textrepo-app:
    container_name: tr_textrepo
    image: knawhuc/textrepo-app:latest
    build: ./textrepo-app
    ports:
    - 8080
    networks:
    - textrepo_network
    command: ["/utils/wait-for-it.sh", "autocomplete-indexer:8080",
              "--timeout=0",
              "--",
              "java", "-jar", "/textrepo-app/textrepo.jar", "server", "config.yml"
    ]

  concordion:
    container_name: tr_concordion
    image: knawhuc/textrepo-concordion:latest
    build: ./concordion
    ports:
    - 8080
    networks:
    - textrepo_network
    command: [
      "/utils/wait-for-it.sh", "textrepo-app:8080",
      "--timeout=0",
      "--",
      # run tests and keep container up:
      "/bin/bash", "-c", "mvn clean test ; tail -f /dev/null"
    ]
    volumes:
    - concordiondata:/concordion
    environment:
      ES_HOST: elasticsearch:9200
      APP_HOST: textrepo-app:8080
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: ${POSTGRES_HOST}
      FILE_INDEX: ${FILE_INDEX}
      CUSTOM_INDEX: ${CUSTOM_INDEX}
      AUTOCOMPLETE_INDEX: ${AUTOCOMPLETE_INDEX}

networks:
  textrepo_network:

volumes:
  esdata:
    driver: local
  concordiondata:
    driver: local
