version: '3.4'

services:
  postgres:
    image: postgres:11-alpine
    networks:
    - textrepo_network
    ports:
    - 5432:5432
    volumes:
    - ./postgres/initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: textrepo
      POSTGRES_DB: textrepo
      POSTGRES_USER: textrepo
      POSTGRES_HOST: postgres.textrepo
      POSTGRES_PORT: 5432

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    environment:
    - node.name=es01
    - cluster.initial_master_nodes=es01
    - cluster.name=textrepo-cluster
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
    - esdata:/usr/share/elasticsearch/data
    ports:
    - 9200:9200
    networks:
    - textrepo_network

  textrepo-app:
    build: ./textrepo-app
    depends_on:
      - "postgres"
    ports:
      - 8080:8080
    networks:
      - textrepo_network
    command: ["/utils/wait-for-it.sh", "postgres:5432", "elasticsearch:9200",
      "--timeout=0",
      "--",
      "java", "-jar", "/textrepo-app/textrepo.jar", "server", "files.yml"]

  integration:
    command: ["/utils/wait-for-it.sh", "textrepo-app:8080",
      "--timeout=0",
      "--",
      "/utils/run-tests.sh"]
    build: ./integration
    networks:
    - textrepo_network
    volumes:
    - ./integration/test:/integration

networks:
  textrepo_network:

volumes:
  esdata:
    driver: local