version: '3.4'

services:
  postgres:
    image: postgres:11-alpine
    networks:
    - textrepo_network
    ports:
    - 5432:5432
    volumes:
    - ./postgres/initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: textrepo
      POSTGRES_DB: textrepo
      POSTGRES_USER: textrepo
      POSTGRES_HOST: postgres.textrepo
      POSTGRES_PORT: 5432

  textrepo-app:
    build: ./textrepo-app
    ports:
      - 8080:8080
    networks:
    - textrepo_network

networks:
  textrepo_network:
