---
kind: Service
apiVersion: v1
metadata:
  name: nginx
  labels:
    textrepo.service: nginx
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    textrepo.service: nginx

---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nginx
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        textrepo.service: nginx
    spec:
      containers:
      - image: knawhuc/textrepo-nginx:latest
        name: nginx
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 200m
            memory: 200Mi
      restartPolicy: Always

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    textrepo.service: nginx-claim1
  name: nginx-claim1
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 200Mi