apiVersion: v1
items:

# Concordion Service
- apiVersion: v1
  kind: Service
  metadata:
    name: concordion
    annotations:
      kompose.cmd: kompose convert -o ./kubernetes/docker-kubernetes.yml
      kompose.version: 1.17.0 (a74acad)
    creationTimestamp: null
    labels:
      io.kompose.service: concordion
  spec:
    ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    selector:
      io.kompose.service: concordion
  status:
    loadBalancer: {}

# Elasticsearch Service
- apiVersion: v1
  kind: Service
  metadata:
    name: elasticsearch
    annotations:
      kompose.cmd: kompose convert -o ./kubernetes/docker-kubernetes.yml
      kompose.version: 1.17.0 (a74acad)
    creationTimestamp: null
    labels:
      io.kompose.service: elasticsearch
  spec:
    ports:
    - name: "9200"
      port: 9200
      targetPort: 9200
    selector:
      io.kompose.service: elasticsearch
  status:
    loadBalancer: {}

# Nginx Service
- apiVersion: v1
  kind: Service
  metadata:
    name: nginx
    annotations:
      kompose.cmd: kompose convert -o ./kubernetes/docker-kubernetes.yml
      kompose.version: 1.17.0 (a74acad)
    creationTimestamp: null
    labels:
      io.kompose.service: nginx
  spec:
    ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    selector:
      io.kompose.service: nginx
  status:
    loadBalancer: {}

# Postgres Service
- apiVersion: v1
  kind: Service
  metadata:
    name: postgres
  spec:
    ports:
    - port: 5432
      targetPort: 5432
  status:
    loadBalancer: {}

# Textrepo-service Service
- apiVersion: v1
  kind: Service
  metadata:
    name: textrepo-app
  spec:
    ports:
    - port: 8080
      targetPort: 8080

# Condordion Deployment
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: concordion
    annotations:
      kompose.cmd: kompose convert -o ./kubernetes/docker-kubernetes.yml
      kompose.version: 1.17.0 (a74acad)
    creationTimestamp: null
    labels:
      io.kompose.service: concordion
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: concordion
      spec:
        containers:
        - args:
          - /utils/wait-for-it.sh
          - textrepo-app:8080
          - --timeout=0
          - --
          - mvn
          - clean
          - test
          env:
          - name: APP_HOST
            value: textrepo-app:8080
          - name: ES_HOST
            value: elasticsearch:9200
          - name: POSTGRES_DB
            value: textrepo
          - name: POSTGRES_HOST
            value: textrepo
          - name: POSTGRES_PASSWORD
            value: textrepo
          - name: POSTGRES_USER
            value: textrepo
          image: knawhuc/textrepo-concordion:latest
          name: concordion
          ports:
          - containerPort: 8080
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 200m
              memory: 200Mi
          volumeMounts:
          - mountPath: /concordion
            name: concordion-claim0
        restartPolicy: Always
        volumes:
        - name: concordion-claim0
          persistentVolumeClaim:
            claimName: concordion-claim0
  status: {}

# Volume
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: concordion-claim0
    name: concordion-claim0
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  status: {}

# Elasticsearch Deployment
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -o ./kubernetes/docker-kubernetes.yml
      kompose.version: 1.17.0 (a74acad)
    creationTimestamp: null
    labels:
      io.kompose.service: elasticsearch
    name: elasticsearch
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: elasticsearch
      spec:
        containers:
        - env:
          - name: ES_JAVA_OPTS
            value: -Xms512m -Xmx512m
          - name: bootstrap.memory_lock
            value: "true"
          - name: cluster.initial_master_nodes
            value: es01
          - name: cluster.name
            value: textrepo-cluster
          - name: node.name
            value: es01
          image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
          name: elasticsearch
          ports:
          - containerPort: 9200
          volumeMounts:
          - mountPath: /usr/share/elasticsearch/data
            name: esdata
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 200m
              memory: 200Mi
        restartPolicy: Always
        volumes:
        - name: esdata
          persistentVolumeClaim:
            claimName: esdata
  status: {}

# PersistentVolumeClaim
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: esdata
    name: esdata
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  status: {}

# Nginx Deployment
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -o ./kubernetes/docker-kubernetes.yml
      kompose.version: 1.17.0 (a74acad)
    creationTimestamp: null
    labels:
      io.kompose.service: nginx
    name: nginx
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: nginx
      spec:
        containers:
        - image: nginx:1.17
          name: nginx
          ports:
          - containerPort: 8080
          volumeMounts:
          - mountPath: /etc/nginx/nginx.conf
            name: nginx-claim0
          - mountPath: /concordion
            name: nginx-claim1
            readOnly: true
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 200m
              memory: 200Mi
        restartPolicy: Always
        volumes:
        - name: nginx-claim0
          persistentVolumeClaim:
            claimName: nginx-claim0
        - name: nginx-claim1
          persistentVolumeClaim:
            claimName: nginx-claim1
            readOnly: true
  status: {}

# Volume
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: nginx-claim0
    name: nginx-claim0
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  status: {}

#Volume
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: nginx-claim1
    name: nginx-claim1
  spec:
    accessModes:
    - ReadOnlyMany
    resources:
      requests:
        storage: 100Mi
  status: {}

# Postgres Deployment
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -o ./kubernetes/docker-kubernetes.yml
      kompose.version: 1.17.0 (a74acad)
    creationTimestamp: null
    labels:
      io.kompose.service: postgres
    name: postgres
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: postgres
      spec:
        containers:
        - env:
          - name: POSTGRES_DB
            value: textrepo
          - name: POSTGRES_HOST
            value: postgres.textrepo
          - name: POSTGRES_PASSWORD
            value: textrepo
          - name: POSTGRES_PORT
            value: textrepo
          - name: POSTGRES_USER
            value: textrepo
          image: postgres:11-alpine
          name: postgres
          ports:
          - containerPort: 5432
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 200m
              memory: 200Mi
          volumeMounts:
          - mountPath: /docker-entrypoint-initdb.d
            name: postgres-claim0
        restartPolicy: Always
        volumes:
        - name: postgres-claim0
          persistentVolumeClaim:
            claimName: postgres-claim0
  status: {}

# Volume
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: postgres-claim0
    name: postgres-claim0
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  status: {}

# Textrepo-app Deployment
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: textrepo-app
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: textrepo-app
      spec:
        containers:
        - args:
          - /utils/wait-for-it.sh
          - postgres:5432
          - elasticsearch:9200
          - --timeout=0
          - --
          - java
          - -jar
          - /textrepo-app/textrepo.jar
          - server
          - config.yml
          image: knawhuc/textrepo-app:latest
          name: textrepo-app
          ports:
          - containerPort: 8080
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 200m
              memory: 200Mi
        restartPolicy: Always
  status: {}
kind: List
metadata: {}

