apiVersion: v1
kind: Secret
metadata:
  name: test-secret
data:
  username: bXktYXBw
  password: Mzk1MjgkdmRnN0pi
  POSTGRES_DB=textrepo
  POSTGRES_HOST=postgres
  POSTGRES_PASSWORD=textrepo
  POSTGRES_PORT=5432
  POSTGRES_USER=textrepo
