version: '3'

services:
  postgres:
    container_name: tr_postgres
    image: knawhuc/textrepo-postgres:${TR_VERSION}
    networks:
      - textrepo_network
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: postgres.textrepo
      POSTGRES_PORT: ${POSTGRES_PORT}
      PGDATA: /var/lib/textrepo/data
    volumes:
      - postgresdata-prod:/var/lib/textrepo/data

  elasticsearch:
    container_name: tr_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    environment:
      - node.name=${ES_NODE_NAME}
      - cluster.initial_master_nodes=${ES_CLUSTER_INITIAL_MASTER_NODES}
      - cluster.name=${ES_CLUSTER_NAME}
      - bootstrap.memory_lock=${ES_BOOTSTRAP_MEMORY_LOCK}
      - ES_JAVA_OPTS=${ES_JAVA_OPTS}
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata-prod:/usr/share/elasticsearch/data
    ports:
      - 9200
    networks:
      - textrepo_network

  nginx:
    container_name: tr_nginx
    image: knawhuc/textrepo-nginx:${TR_VERSION}
    networks:
      - textrepo_network
    depends_on:
      - textrepo-app
    volumes:
      - concordiondata:/concordion:ro
    ports:
      - ${NGINX_LISTEN}:${NGINX_LISTEN}
    environment:
      VIRTUAL_HOST: ${NGINX_VIRTUAL_HOST}
      NGINX_LISTEN: ${NGINX_LISTEN}
      NGINX_LOCATION: ${NGINX_LOCATION}
      NGINX_ROOT_REDIRECT: ${NGINX_ROOT_REDIRECT}

  autocomplete-indexer:
    container_name: tr_autocomplete
    image: knawhuc/textrepo-autocomplete-indexer:${TR_VERSION}
    ports:
      - 8080
    networks:
      - textrepo_network
    command: ["/utils/wait-for-it.sh", "elasticsearch:9200",
              "--timeout=0",
              "--",
              "java", "-jar", "/indexer/autocomplete.jar", "server", "config.yml"]

  full-text-indexer:
    container_name: tr_full-text
    image: knawhuc/textrepo-full-text-indexer:${TR_VERSION}
    ports:
      - 8080
    networks:
      - textrepo_network
    command: ["/utils/wait-for-it.sh", "elasticsearch:9200",
              "--timeout=0",
              "--",
              "java", "-jar", "/indexer/full-text.jar", "server", "config.yml"]

  textrepo-app:
    container_name: tr_textrepo
    image: knawhuc/textrepo-app:${TR_VERSION}
    ports:
      - 8080
      - 8081:8081
    networks:
      - textrepo_network
    command: ["./wait-for-it.sh", "autocomplete-indexer:8080", "--timeout=0", "--",
              "./wait-for-it.sh", "postgres:${POSTGRES_PORT}", "--timeout=0", "--",
              "./start.sh"
              ]
    environment:
      TR_DATABASE_DRIVER_CLASS: ${TR_DATABASE_DRIVER_CLASS}
      TR_DATABASE_USER: ${TR_DATABASE_USER}
      TR_DATABASE_PASSWORD: ${TR_DATABASE_PASSWORD}
      TR_DATABASE_URL: ${TR_DATABASE_URL}
      TR_DATABASE_PROPERTIES_CHAR_SET: ${TR_DATABASE_PROPERTIES_CHAR_SET}
      TR_DATABASE_MAX_WAIT_FOR_CONNECTION: ${TR_DATABASE_MAX_WAIT_FOR_CONNECTION}
      TR_DATABASE_VALIDATION_QUERY_TIMEOUT: ${TR_DATABASE_VALIDATION_QUERY_TIMEOUT}
      TR_DATABASE_MIN_SIZE: ${TR_DATABASE_MIN_SIZE}
      TR_DATABASE_MAX_SIZE: ${TR_DATABASE_MAX_SIZE}
      TR_DATABASE_CHECK_CONNECTION_WHILE_IDLE: ${TR_DATABASE_CHECK_CONNECTION_WHILE_IDLE}
      TR_DATABASE_EVICTION_INTERVAL: ${TR_DATABASE_EVICTION_INTERVAL}
      TR_LOGGING_LEVEL: ${TR_LOGGING_LEVEL}
      TR_LOGGING_LOGGERS: ${TR_LOGGING_LOGGERS}
      TR_LOGGING_APPENDERS: ${TR_LOGGING_APPENDERS}
      TR_INDEXERS: ${TR_INDEXERS}
      TR_SWAGGER_RESOURCE_PACKAGE: ${TR_SWAGGER_RESOURCE_PACKAGE}
      TR_SWAGGER_CONTEXT_ROOT: ${TR_SWAGGER_CONTEXT_ROOT}
      TR_SWAGGER_SCHEMES: ${TR_SWAGGER_SCHEMES}
      TR_PAGINATION_DEFAULT_OFFSET: ${TR_PAGINATION_DEFAULT_OFFSET}
      TR_PAGINATION_DEFAULT_LIMIT: ${TR_PAGINATION_DEFAULT_LIMIT}
      TR_DATE_FORMAT: ${TR_DATE_FORMAT}

networks:
  textrepo_network:

volumes:
  esdata-prod:
    driver: local
  postgresdata-prod:
    driver: local
  # display test results from non-production volume:
  concordiondata:
    driver: local
