database:
  driverClass: org.postgresql.Driver
  user: textrepo
  password: textrepo
  url: jdbc:postgresql://postgres:5432/textrepo
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute

logging:
  level: INFO
  loggers:
    nl.knaw.huc: DEBUG

elasticsearch:
  # Hosts must be a list of hosts in the Elasticsearch cluster.
  # The format is <hostname> or <hostname>:<port>. The port defaults to 9200.
  hosts:
    - elasticsearch:9200
  index: documents
  contentField: content

customFacetIndexer:
  mapping: http://localhost:8080/custom-index/kranten1700/mapping
  fields: http://localhost:8080/custom-index/kranten1700/fields
  elasticsearch:
    index: custom-facet
    contentField: content
    hosts:
      - elasticsearch:9200

swagger:
  resourcePackage: nl.knaw.huc.resources
