database:
  driverClass: org.postgresql.Driver
  user: textrepo
  password: textrepo
  url: jdbc:postgresql://postgres:5432/textrepo
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute

logging:
  level: INFO
  loggers:
    nl.knaw.huc: DEBUG
    # Filter out flood of warnings when Swagger tries to load classes through reflection:
    org.reflections.Reflections: ERROR

elasticsearch:
  # Hosts must be a list of hosts in the Elasticsearch cluster.
  # The format is <hostname> or <hostname>:<port>. The port defaults to 9200.
  hosts:
    - elasticsearch:9200
  index: files
  contentField: content

customFacetIndexers:
- mapping: https://demo.gekaaptebrieven.diginfra.net/api/projects/gekaaptebrieven/mapping
  fields:
    url: https://demo.gekaaptebrieven.diginfra.net/api/projects/gekaaptebrieven/documents/x/fields
    type: urlencoded
  mimetypes:
    - application/xml
  elasticsearch:
    index: custom-facet
    contentField: content
    hosts:
      - elasticsearch:9200
- mapping: http://autocomplete-indexer:8080/autocomplete/mapping
  fields:
    url: http://autocomplete-indexer:8080/autocomplete/fields
    type: multipart
  mimetypes:
    - application/xml
    - text/plain
  elasticsearch:
    index: autocomplete
    contentField: content
    hosts:
      - elasticsearch:9200

swagger:
  resourcePackage: nl.knaw.huc.resources
  contextRoot: /textrepo
