database:
  driverClass: ${TR_DATABASE_DRIVER_CLASS}
  user: ${TR_DATABASE_USER}
  password: ${TR_DATABASE_PASSWORD}
  url: ${TR_DATABASE_URL}
  properties:
    charSet: ${TR_DATABASE_PROPERTIES_CHAR_SET}
  maxWaitForConnection: ${TR_DATABASE_MAX_WAIT_FOR_CONNECTION}
  validationQueryTimeout: ${TR_DATABASE_VALIDATION_QUERY_TIMEOUT}
  minSize: ${TR_DATABASE_MIN_SIZE}
  maxSize: ${TR_DATABASE_MAX_SIZE}
  checkConnectionWhileIdle: ${TR_DATABASE_CHECK_CONNECTION_WHILE_IDLE}
  evictionInterval: ${TR_DATABASE_EVICTION_INTERVAL}
logging:
  level: ${TR_LOGGING_LEVEL}
  loggers: ${TR_LOGGING_LOGGERS}
  appenders: ${TR_LOGGING_APPENDERS}
indexers: ${TR_INDEXERS}
limits:
  contentDecompressionLimit: ${TR_CONTENT_DECOMPRESSION_LIMIT}
swagger:
  schemes: ${TR_SWAGGER_SCHEMES}
  resourcePackage: ${TR_SWAGGER_RESOURCE_PACKAGE}
  contextRoot: ${TR_SWAGGER_CONTEXT_ROOT}
pagination:
  defaultOffset: ${TR_PAGINATION_DEFAULT_OFFSET}
  defaultLimit: ${TR_PAGINATION_DEFAULT_LIMIT}
dateFormat: ${TR_DATE_FORMAT}
