version: '3.2'

services:
  pg:
    image: postgres:11-alpine
    networks:
    - textrepo_network
    ports:
    - 5432:5432
    volumes:
    - ./initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: textrepo
      POSTGRES_DB: textrepo
      POSTGRES_USER: textrepo
      POSTGRES_HOST: pg.textrepo
      POSTGRES_PORT: 5432

networks:
  textrepo_network:

