name: Build 🛠️ TextRepo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install build environment
        run: |
             echo "workspace: $GITHUB_WORKSPACE, cwd: $CWD"
             if [ "$RUNNER_OS" == "Linux" ]; then
               echo "Linux build"
               sudo apt-get install docker
             fi
             . $GITHUB_WORKSPACE/examples/development/docker-compose.env
             docker compose -f $GITHUB_WORKSPACE/examples/development/docker-compose.yml build
