name: Build 🛠️ TextRepo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install build environment
        run: |
             echo "workspace: $GITHUB_WORKSPACE, cwd: $CWD"
             echo "PATH: $PATH"
             which docker
             type docker
             whereis docker
             /usr/bin/docker -v
             /usr/local/bin/docker -v
             /opt/bin/docker -v
             if [ "$RUNNER_OS" == "Linux" ]; then
               echo "Linux build"
             fi
               
      - name: Build docker files
        run: |
             cd $GITHUB_WORKSPACE
             . ./examples/development/docker-compose.env
             docker compose -f ./examples/development/docker-compose.yml build
